#! /bin/bash

#Intial
run_dir=$(pwd)
prod_dir=$run_dir/production
equi_dir=$run_dir/equilibration
npt_dir=$equi_dir/2-NPT

###################################
#            Analysis             #
###################################
printf "\n\n4- Analysis\n"
ana_dir=$run_dir/analysis
mkdir -p $ana_dir
echo "    Directory $ana_dir created"
cd $ana_dir
echo "    Center the protein and remove the water from the trajectory"
#Copy files
ln -s $npt_dir/npt.tpr .
ln -s $prod_dir/prod.xtc .
ln -s $prod_dir/prod.gro .
#Compact system
    #XTC
echo 'Protein' 'System' | gmx trjconv -s npt.tpr -f prod.xtc -pbc mol -ur compact -center -o prod_compact.xtc
    #GRO
echo 'Protein' 'System' | gmx trjconv -s npt.tpr -f prod.gro -pbc mol -ur compact -center -o prod_compact.gro
#Protein center
    #XTC
echo 'Protein' 'Protein' | gmx trjconv -s npt.tpr -f prod_compact.xtc -pbc mol -ur compact -center -o prod_prot_center.xtc
#Remove rotation
    #XTC
echo 'Backbone' 'Protein' | gmx trjconv -s npt.tpr -f prod_prot_center.xtc -fit rot+trans -o prod_prot_fit.xtc
    #GRO
echo 'Backbone' 'Protein' | gmx trjconv -s npt.tpr -f prod_compact.gro -fit rot+trans -o prod_prot_fit.gro

echo "    Analysis done !"
