#! /bin/bash

#Intial
run_dir=$(pwd)
prod_dir=$run_dir/production
python_water_code_dir=$1

###################################
#            Analysis             #
###################################
printf "\n\n4- Analysis\n"
mkdir -p $run_dir/analysis
ana_dir=$run_dir/analysis
echo "    Directory $ana_dir created"
cd $ana_dir
echo "    Water analysis..."
#Copy files
ln -s $prod_dir/prod.edr .
#Runing gmx energy
echo -e 'Density' | gmx energy -f prod.edr -o density.xvg
#Runing gmx analyse
gmx analyze -f density.xvg -ac density_autocorr -ee
#Runing python analysis
$python_water_code_dir --volume -f density.xvg -e errest.xvg --pdf molar_volume.pdf --txt time_volume_mean_error.txt
echo "    Analysis done !"
