#! /bin/bash

#Intial
run_dir=$(pwd)
input_dir=$run_dir/input
minim_dir=$run_dir/minimization
number_core=$1
GMX_EXE=$2
MPRUN_EXE=$3

###################################
#          Equilibration          #
###################################

printf "\n\n2- Equilibration step\n"
mkdir -p $run_dir/equilibration
equi_dir=$run_dir/equilibration
echo "    Directory $equi_dir created"
cd $equi_dir

    #-----#
    # NVT #
    #-----#
echo "    2-1 NVT equilibration"
mkdir -p $equi_dir/1-NVT
nvt_dir=$equi_dir/1-NVT
echo "        Directory $nvt_dir created"
cd $nvt_dir
#Copy files
cp $input_dir/nvt.mdp .
ln -s $minim_dir/em.gro .
ln -s $input_dir/topol.top .
ln -s $input_dir/index.ndx .
#Running gmx
echo "        Running gmx grompp"
$GMX_EXE grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr -n index.ndx
echo "    Running gmx mdrun"
$MPRUN_EXE $GMX_EXE mdrun -v -deffnm nvt -nt $number_core
echo "        NVT equilibration done."
cd $equi_dir

    #-----#
    # NPT #
    #-----#
echo "    2-2 NPT equilibration"
mkdir -p $equi_dir/2-NPT
npt_dir=$equi_dir/2-NPT
echo "        Directory $npt_dir created"
cd $npt_dir
#Copy file
cp $input_dir/npt.mdp .
ln -s $nvt_dir/nvt.gro .
ln -s $nvt_dir/nvt.cpt .
ln -s $input_dir/topol.top .
ln -s $input_dir/index.ndx .
#Running gmx
echo "        Running gmx grompp"
$GMX_EXE grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr -n index.ndx
echo "    Running gmx mdrun"
$MPRUN_EXE $GMX_EXE mdrun -v -deffnm npt -nt $number_core
echo "        NPT equilibration done."
cd $equi_dir