#! /bin/bash

#Intial
run_dir=$(pwd)
input_dir=$run_dir/input
minim_dir=$run_dir/minimization
equi_dir=$run_dir/equilibration
npt_dir=$equi_dir/2-NPT
number_core=$1
GMX_EXE=$2
MPRUN_EXE=$3


###################################
#             MD Run              #
###################################

printf "\n\n3- MD run\n"
mkdir -p $run_dir/production
prod_dir=$run_dir/production
echo "    Directory $prod_dir created"
cd $prod_dir
#Copy files
cp $input_dir/prod.mdp .
ln -s $npt_dir/npt.gro .
ln -s $npt_dir/npt.cpt .
ln -s $input_dir/topol.top .
ln -s $input_dir/index.ndx .
#Running gmx
echo "        Running gmx grompp"
$GMX_EXE grompp -f prod.mdp -c npt.gro -t npt.cpt -p topol.top -o prod.tpr -n index.ndx
echo "    Running gmx mdrun"
$MPRUN_EXE $GMX_EXE mdrun -deffnm prod -nt $number_core
echo "        Production run done."
cd $run_dir