#! /bin/bash

#Intial
run_dir=$(pwd)
input_dir=$run_dir/input
minim_dir=$run_dir/minimization
equi_dir=$run_dir/equilibration
npt_dir=$equi_dir/2-NPT


###################################
#             MD Run              #
###################################

printf "\n\n3- MD run\n"
mkdir -p $run_dir/production
prod_dir=$run_dir/production
echo "    Directory $prod_dir created"
cd $prod_dir
#Copy files
cp $input_dir/prod.mdp .
cp $npt_dir/npt.gro .
cp $npt_dir/npt.cpt .
cp $input_dir/topol.top .
cp $input_dir/index.ndx .
#Running gmx
echo "        Running gmx grompp"
gmx grompp -f prod.mdp -c npt.gro -t npt.cpt -p topol.top -o prod.tpr -n index.ndx
echo "    Running gmx mdrun"
gmx mdrun -v -deffnm prod
echo "        Production run done."
cd $run_dir