#! /bin/bash

#Intial
run_dir=$(pwd)
echo "Working directory: $run_dir"
input_dir=$run_dir/input
echo "Input directory: $input_dir"

code_dir=/home/ccattin/Documents/A3/Stage/Code
gmx_code_dir=$code_dir/GMX
python_water_code_dir=$code_dir/water/eau_CLI.py

##################################
#          Minimization          #
##################################
$gmx_code_dir/minimization
cd $run_dir

###################################
#          Equilibration          #
###################################
$gmx_code_dir/equilibration
cd $run_dir

###################################
#             MD Run              #
###################################
$gmx_code_dir/production
cd $run_dir

###################################
#            Analysis             #
###################################
$gmx_code_dir/analysis_water $python_water_code_dir
