#!/bin/bash

# Set the new job name
new_job_name=$1

#Submit script
submit=$2

if [ -z "$submit" ]
then
    echo "Please provide a correct submit file"
    exit 0
fi

# Change the job name in the submit file
sed -i "s/#SBATCH --job-name=.*/#SBATCH --job-name=${new_job_name}/" $submit
