#! /bin/bash

#Intial
run_dir=$(pwd)
echo "Working directory: $run_dir"
input_dir=$run_dir/input
echo "Input directory: $input_dir"

number_core=$1

code_dir=/home/ccattin/Stage/Code
gmx_code_dir=$code_dir/GMX
python_water_code_dir=$code_dir/water/eau_CLI.py

##################################
#          Minimization          #
##################################
$gmx_code_dir/minimization $number_core
cd $run_dir

###################################
#          Equilibration          #
###################################
$gmx_code_dir/equilibration $number_core
cd $run_dir

###################################
#             MD Run              #
###################################
$gmx_code_dir/production $number_core
cd $run_dir

###################################
#            Analysis             #
###################################
#$gmx_code_dir/analysis_water $python_water_code_dir
cd $run_dir
$gmx_code_dir/analysis_center_prot
cd $run_dir