#! /bin/bash

#Intial
run_dir=$(pwd)
echo "Working directory: $run_dir"
input_dir=$run_dir/input
echo "Input directory: $input_dir"

nMPI=$1
nOMP=$2
GMX_EXE=$3
MPRUN_EXE=$4

code_dir=/home/ccattin/Stage/Code
gmx_code_dir=$code_dir/GMX
python_water_code_dir=$code_dir/water/eau_CLI.py

##################################
#          Minimization          #
##################################
printf "\n1 - Minimization step\n"
minim_dir=$run_dir/minimization
mkdir -p $minim_dir

echo "    Directory $minim_dir created"
cd $minim_dir
#Copy files
cp $input_dir/minim.mdp .
ln -s $input_dir/input.gro .
ln -s $input_dir/input.pdb .
ln -s $input_dir/topol.top .
#Running gmx
echo "    Running gmx grompp"
$GMX_EXE grompp -f minim.mdp -c input.gro -p topol.top -o em.tpr
echo "    Running gmx mdrun"
$MPRUN_EXE -np $nMPI $GMX_EXE mdrun -ntomp $nOMP -deffnm em
echo "    Energy minimization done."
cd $run_dir
sleep 3

###################################
#          Equilibration          #
###################################
printf "\n\n2- Equilibration step\n"
mkdir -p $run_dir/equilibration
equi_dir=$run_dir/equilibration
echo "    Directory $equi_dir created"
cd $equi_dir

    #-----#
    # NVT #
    #-----#
echo "    2-1 NVT equilibration"
mkdir -p $equi_dir/1-NVT
nvt_dir=$equi_dir/1-NVT
echo "        Directory $nvt_dir created"
cd $nvt_dir
#Copy files
cp $input_dir/nvt.mdp .
ln -s $minim_dir/em.gro .
ln -s $input_dir/topol.top .
ln -s $input_dir/index.ndx .
#Running gmx
echo "        Running gmx grompp"
$GMX_EXE grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr -n index.ndx
echo "    Running gmx mdrun"
$MPRUN_EXE -np $nMPI $GMX_EXE mdrun -ntomp $nOMP -deffnm nvt
echo "        NVT equilibration done."
cd $equi_dir

    #-----#
    # NPT #
    #-----#
echo "    2-2 NPT equilibration"
mkdir -p $equi_dir/2-NPT
npt_dir=$equi_dir/2-NPT
echo "        Directory $npt_dir created"
cd $npt_dir
#Copy file
cp $input_dir/npt.mdp .
ln -s $nvt_dir/nvt.gro .
ln -s $nvt_dir/nvt.cpt .
ln -s $input_dir/topol.top .
ln -s $input_dir/index.ndx .
#Running gmx
echo "        Running gmx grompp"
$GMX_EXE grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr -n index.ndx
echo "    Running gmx mdrun"
$MPRUN_EXE -np $nMPI $GMX_EXE mdrun -ntomp $nOMP -deffnm npt
echo "        NPT equilibration done."
cd $equi_dir

###################################
#             MD Run              #
###################################
printf "\n\n3- MD run\n"
mkdir -p $run_dir/production
prod_dir=$run_dir/production
echo "    Directory $prod_dir created"
cd $prod_dir
#Copy files
cp $input_dir/prod.mdp .
ln -s $npt_dir/npt.gro .
ln -s $npt_dir/npt.cpt .
ln -s $input_dir/topol.top .
ln -s $input_dir/index.ndx .
#Running gmx
echo "        Running gmx grompp"
$GMX_EXE grompp -f prod.mdp -c npt.gro -t npt.cpt -p topol.top -o prod.tpr -n index.ndx
echo "    Running gmx mdrun"
$MPRUN_EXE -np $nMPI $GMX_EXE mdrun -ntomp $nOMP -deffnm prod
echo "        Production run done."
cd $run_dir

###################################
#            Analysis             #
###################################
$gmx_code_dir/analysis_center_prot
